
---
#
# Installing Bind DNS
#

# Install Bind DNS
- name: Install Bind bind9
  apt:
    name: bind9
    update_cache: yes

# Install Bind bind9utils
- name: Install Bind bind9utils
  apt:
    name: bind9utils
    update_cache: yes

# Install Bind bind9-doc
- name: Install bind9-doc
  apt:
    name: bind9-doc
    update_cache: yes

# Enable bind9 service
- name: Enabling bind9 service
  systemd:
    name: bind9
    enabled: yes

# Start bind9 service
- name: Starting bind9 service
  systemd:
    name: bind9
    state: started
    daemon_reload: yes
