---
#
# Installing Nginx
#

# Install Nginx
- name: Update repositories cache and install Nginx
  apt:
    name: bind9 bind9utils bind9-doc
    update_cache: yes

# Enable bind9 service
- name: Enabling bind9 service
  systemd:
    name: bind9
    enabled: yes
  notify: enable bind9

# Start bind9 service
- name: Starting bind9 service
  systemd:
    name: bind9
    state: started
    daemon_reload: yes
  notify: start bind9
