
---
#
# Installing Bind DNS
#

# Install Bind DNS
- name: Install Bind DNS
  apt:
    name: bind9 bind9utils bind9-doc
    update_cache: yes

# Enable bind9 service
- name: Enabling bind9 service
  systemd:
    name: bind9
    enabled: yes

# Start bind9 service
- name: Starting bind9 service
  systemd:
    name: bind9
    state: started
    daemon_reload: yes
