
---
#
# Installing Bind DNS
#

# Install Bind DNS
- name: Install Bind DNS
  apt:
    name: {{item}}
    update_cache: yes
    with_items:
        - bind9
        - bind9utils
        - bind9-doc

# Enable bind9 service
- name: Enabling bind9 service
  systemd:
    name: bind9
    enabled: yes

# Start bind9 service
- name: Starting bind9 service
  systemd:
    name: bind9
    state: started
    daemon_reload: yes
