
---
#
# Setup DNS and IP
#

# Create static interfaces entry
- name: Create static interfaces entry
  template:
    src=named.conf.options.j2
    dest=/etc/bind/named.conf.options
    owner=root
    group=root
    mode=0644
