---
#
# Nginx Handlers
#

# Enable nginx service
- name: Enabling Nginx service
  systemd:
    name: nginx
    enabled: yes
  notify: enable nginx

# Restart Nginx service
- name: Restart Nginx service
  systemd:
    name: nginx
    state: reloaded
    daemon_reload: yes
  notify: restart nginx

# Start Nginx service
- name: Starting Nginx service
  systemd:
    name: nginx
    state: started
    daemon_reload: yes
  notify: start nginx
